export const POINT_DEFINITIONS: { [key: string]: { x: number; y: number; view: 'front' | 'back'; offset?: number } } = {
  // Cabeça
  'Parietal Direito': { x: 40, y: 20, view: 'front' },
  'Parietal Esquerdo': { x: 60, y: 20, view: 'front' },
  'Parietal (D/E)': { x: 50, y: 20, view: 'front', offset: 10 },
  'Pineal': { x: 50, y: 22, view: 'front' },
  'Prepineal': { x: 50, y: 20, view: 'front' },
  'Pospineal': { x: 50, y: 22, view: 'back' },
  'Pospinel': { x: 50, y: 22, view: 'back' },
  'Borda Calloso (D/E)': { x: 50, y: 18, view: 'front', offset: 8 },
  'Borda Calloso': { x: 50, y: 18, view: 'front' },
  'Hipófise': { x: 50, y: 25, view: 'front' },
  'Bulbo Raquidiano': { x: 50, y: 28, view: 'back' },
  'Bulbo raquidiano': { x: 50, y: 28, view: 'back' },
  'Cerebelo (C)': { x: 50, y: 24, view: 'back' },
  'Cerebelo': { x: 50, y: 24, view: 'back' },
  'Cerebelo (D/E)': { x: 50, y: 24, view: 'back', offset: 6 },
  'Occipital': { x: 50, y: 18, view: 'back' },
  'Occipital (D/E)': { x: 50, y: 18, view: 'back', offset: 6 },
  'Temporal': { x: 50, y: 22, view: 'front', offset: 12 },
  'Temporal (D)': { x: 38, y: 22, view: 'front' },
  'Temporal (D/E)': { x: 50, y: 22, view: 'front', offset: 12 },
  'Temporal D': { x: 38, y: 22, view: 'front' },
  'Temporal E': { x: 62, y: 22, view: 'front' },
  'Temporoccipital (D)': { x: 40, y: 21, view: 'back' },
  'Temporoccipital (E)': { x: 60, y: 21, view: 'back' },
  'Seio frontal (D)': { x: 44, y: 18, view: 'front' },
  'Seio frontal (E)': { x: 56, y: 18, view: 'front' },
  'Interciliar': { x: 50, y: 18, view: 'front' },
  'Supraciliar': { x: 50, y: 16, view: 'front' },
  'Seio paranasal (D)': { x: 44, y: 28, view: 'front' },
  'Seio paranasal (E)': { x: 56, y: 28, view: 'front' },
  'Polo (D)': { x: 40, y: 14, view: 'front' },
  'Polo (E)': { x: 60, y: 14, view: 'front' },
  'Craneal (D)': { x: 35, y: 12, view: 'front' },
  'Craneal (E)': { x: 65, y: 12, view: 'front' },
  'Lacrimal (D)': { x: 48, y: 24, view: 'front' },
  'Lacrimal (E)': { x: 52, y: 24, view: 'front' },
  'Canto do olho (D)': { x: 46, y: 24, view: 'front' },
  'Canto do olho (E)': { x: 54, y: 24, view: 'front' },
  'Pálpebra (D)': { x: 43, y: 24, view: 'front' },
  'Pálpebra (E)': { x: 57, y: 24, view: 'front' },
  'Piso orbital (D)': { x: 45, y: 26, view: 'front' },
  'Piso orbital (E)': { x: 55, y: 26, view: 'front' },
  'Piso Orbital': { x: 50, y: 26, view: 'front', offset: 5 },
  'Quiasma (D)': { x: 47, y: 22, view: 'front' },
  'Quiasma (E)': { x: 53, y: 22, view: 'front' },
  'Polígono de Willis (D)': { x: 44, y: 22, view: 'front' },
  'Polígono de Willis (E)': { x: 56, y: 22, view: 'front' },
  'Polígono de Willis': { x: 50, y: 22, view: 'front', offset: 6 },
  'Nariz (D)': { x: 48, y: 28, view: 'front' },
  'Nariz (E)': { x: 52, y: 28, view: 'front' },
  'Malar (D)': { x: 42, y: 30, view: 'front' },
  'Malar (E)': { x: 58, y: 30, view: 'front' },
  'Maxilar Superior (D)': { x: 46, y: 31, view: 'front' },
  'Maxilar Superior (E)': { x: 54, y: 31, view: 'front' },
  'Ângulo (D)': { x: 39, y: 33, view: 'front' },
  'Ângulo (E)': { x: 61, y: 33, view: 'front' },
  'Canto da boca (D)': { x: 46, y: 32, view: 'front' },
  'Canto da boca (E)': { x: 54, y: 32, view: 'front' },
  'Ouvido Direito': { x: 38, y: 26, view: 'front' },
  'Ouvido Esquerdo': { x: 62, y: 26, view: 'front' },
  'Ouvido (D/E)': { x: 50, y: 26, view: 'front', offset: 12 },
  'Orelha (D/E)': { x: 50, y: 26, view: 'front', offset: 14 },
  'Mastoide (D/E)': { x: 50, y: 27, view: 'back', offset: 10 },
  'Pômulo (D/E) osso zigomático': { x: 50, y: 29, view: 'front', offset: 10 },
  'Língua (D/E)': { x: 50, y: 32, view: 'front', offset: 5 },
  'Língua (D ou E)': { x: 50, y: 32, view: 'front' },
  'Língua': { x: 50, y: 32, view: 'front' },
  'Mandíbula (D/E)': { x: 50, y: 34, view: 'front', offset: 10 },
  'Parótida (D/E)': { x: 50, y: 30, view: 'front', offset: 12 },
  'Olho (D/E)': { x: 50, y: 24, view: 'front', offset: 5 },
  'Pinta': { x: 50, y: 15, view: 'front' },
  'Sobrancelha (D)': { x: 43, y: 21, view: 'front' },
  'Sobrancelha (E)': { x: 57, y: 21, view: 'front' },
  'Preauricular': { x: 50, y: 26, view: 'front', offset: 12 },
  'Antecuerno (D)': { x: 44, y: 10, view: 'front' },
  'Antecuerno (E)': { x: 56, y: 10, view: 'front' },

  // Pescoço / Tórax (Frente)
  'Amígdala palatina (Angina)': { x: 50, y: 35, view: 'front', offset: 4 },
  'Amígdala palatina (Angina) (D/E)': { x: 50, y: 35, view: 'front', offset: 4 },
  'Pescoço': { x: 50, y: 36, view: 'front' },
  'Pescoço (D/E)': { x: 50, y: 36, view: 'front', offset: 8 },
  'Plexo Cervical': { x: 50, y: 34, view: 'front', offset: 10 },
  'Laringe': { x: 50, y: 38, view: 'front' },
  'Laringe (S)': { x: 50, y: 37, view: 'front' },
  'Laringe (Inf)': { x: 50, y: 39, view: 'front' },
  'Esterno cleido mastoideo (D)': { x: 44, y: 36, view: 'front' },
  'Esterno cleido mastoideo (E)': { x: 56, y: 36, view: 'front' },
  'Carótida': { x: 50, y: 38, view: 'front', offset: 3 },
  'Carótida (D)': { x: 47, y: 38, view: 'front' },
  'Carótida (E)': { x: 53, y: 38, view: 'front' },
  'Primeira Costela': { x: 50, y: 42, view: 'front', offset: 8 },
  'Primeira Costela (D)': { x: 42, y: 42, view: 'front' },
  'Primeira Costela (E)': { x: 58, y: 42, view: 'front' },
  'Manubrio de Esterno': { x: 50, y: 41, view: 'front', offset: 3 },
  'Esterno': { x: 50, y: 55, view: 'front' },
  'Traqueia': { x: 50, y: 41, view: 'front' },
  'Traqueia (D/E)': { x: 50, y: 38, view: 'front', offset: 3 },
  'Esôfago': { x: 50, y: 50, view: 'front' },
  'Esôfago (E)': { x: 52, y: 50, view: 'front' },
  'Esôfago (D)': { x: 48, y: 50, view: 'front' },
  'Cardias': { x: 48, y: 56, view: 'front' },
  'Cárdia': { x: 48, y: 56, view: 'front' },
  'Hiato esofágico': { x: 50, y: 58, view: 'front' },
  'Hiato esofagico': { x: 50, y: 58, view: 'front' },
  'Carina': { x: 50, y: 43, view: 'front', offset: 5 },
  'Carina (D)': { x: 45, y: 43, view: 'front' },
  'Carina (E)': { x: 55, y: 43, view: 'front' },
  'Timo': { x: 50, y: 40, view: 'front' },
  'Timo (Sup)': { x: 50, y: 39, view: 'front' },
  'Timo (Inf)': { x: 50, y: 41, view: 'front' },
  'Nervo Vago': { x: 50, y: 35, view: 'front' },
  'Nervo Vago (D/E)': { x: 50, y: 35, view: 'front', offset: 5 },
  'Clavícula Média': { x: 50, y: 38, view: 'front', offset: 10 },
  'Axila': { x: 50, y: 45, view: 'front', offset: 20 },
  'Axila (D/E)': { x: 50, y: 45, view: 'front', offset: 20 },
  'Subclávia (D/E)': { x: 50, y: 41, view: 'front', offset: 10 },
  'Mediastino (Sup)': { x: 50, y: 45, view: 'front' },
  'Mediastino (inf)': { x: 50, y: 50, view: 'front' },
  'Mama': { x: 50, y: 50, view: 'front' },
  'Pericárdio': { x: 47, y: 52, view: 'front' },
  'Coronárias': { x: 45, y: 52, view: 'front' },
  'Botão Aórtico': { x: 50, y: 42, view: 'front' },
  'Sino(nodo) Atrioventricular': { x: 48, y: 53, view: 'front' },
  'Peitoral (D)': { x: 38, y: 46, view: 'front' },
  'Peitoral (E)': { x: 62, y: 46, view: 'front' },
  
  // Tronco (Abdômen/Órgãos)
  'Subdiafragma (D)': { x: 38, y: 58, view: 'front' },
  'Subdiafragma (E)': { x: 62, y: 58, view: 'front' },
  'Estômago': { x: 58, y: 62, view: 'front' },
  'Fígado': { x: 42, y: 62, view: 'front' },
  'Apêndice': { x: 42, y: 78, view: 'front' },
  'Bexiga': { x: 50, y: 84, view: 'front' },
  'Sigmóide': { x: 58, y: 76, view: 'front' },
  'Cólon sigmoide': { x: 58, y: 76, view: 'front' },
  'Xifoide': { x: 50, y: 60, view: 'front' },
  'Uretra Sup': { x: 50, y: 86, view: 'front' },
  'Uretra inf': { x: 50, y: 90, view: 'front' },
  'Uretra (Sup)': { x: 50, y: 86, view: 'front' },
  'Uretra (inf)': { x: 50, y: 90, view: 'front' },
  'Pâncreas': { x: 52, y: 65, view: 'front' },
  'Pancreas': { x: 52, y: 65, view: 'front' },
  'Cabeça de pâncreas': { x: 55, y: 65, view: 'front' },
  'Cabeça do Pancreas': { x: 55, y: 65, view: 'front' },
  'Pâncreas (Corpo)': { x: 52, y: 65, view: 'front' },
  'Cauda do Pâncreas': { x: 60, y: 63, view: 'front' },
  'Cauda de pâncreas': { x: 60, y: 63, view: 'front' },
  'Ponta do pâncreas': { x: 62, y: 62, view: 'front' },
  'Ligamento pancreático': { x: 55, y: 68, view: 'front' },
  'Ligamento do Pâncreas': { x: 55, y: 68, view: 'front' },
  'Peripancreático (S)': { x: 52, y: 63, view: 'front' },
  'Peripancreático (Inf)': { x: 52, y: 67, view: 'front' },
  'Ampola Hepatopancreática': { x: 50, y: 66, view: 'front' },
  'Piloro': { x: 50, y: 68, view: 'front' },
  'Colon Ascendente': { x: 42, y: 72, view: 'front', offset: 2 },
  'Cólon ascendente': { x: 42, y: 72, view: 'front', offset: 2 },
  'Cólon transverso': { x: 50, y: 70, view: 'front' },
  'Colon Transverso': { x: 50, y: 70, view: 'front' },
  'Cólon descendente': { x: 58, y: 72, view: 'front' },
  'Colon Descendente': { x: 58, y: 72, view: 'front' },
  'Baço': { x: 60, y: 60, view: 'front' },
  'Duodeno': { x: 50, y: 67, view: 'front' },
  'Vesícula biliar': { x: 45, y: 64, view: 'front' },
  'Conduto da vesícula (ducto biliar)': { x: 45, y: 65, view: 'front' },
  'Conduto Pancreático': { x: 55, y: 66, view: 'front' },
  'Válvula ileocecal': { x: 45, y: 76, view: 'front' },
  'Ceco': { x: 42, y: 77, view: 'front' },
  'Contraceco': { x: 58, y: 77, view: 'front' },
  'Ureter (D ou E)': { x: 50, y: 78, view: 'front' },
  'Ureter (D/E)': { x: 50, y: 78, view: 'front', offset: 5 },
  'Ureter mesmo lado': { x: 50, y: 78, view: 'front' },
  'Útero': { x: 50, y: 82, view: 'front', offset: 2 },
  'Ovário (D ou E)': { x: 50, y: 80, view: 'front' },
  'Ovário (D/E)': { x: 50, y: 80, view: 'front', offset: 8 },
  'Trompa (D/E)': { x: 50, y: 81, view: 'front', offset: 6 },
  'Trompa de Falópio (D/E)': { x: 50, y: 81, view: 'front', offset: 6 },
  'Vagina': { x: 50, y: 86, view: 'front' },
  'Testículo/vagina (D/E)': { x: 50, y: 88, view: 'front', offset: 4 },
  'Testículo/vagina': { x: 50, y: 88, view: 'front' },
  'Próstata/períneo': { x: 50, y: 87, view: 'front' },
  'Próstata': { x: 50, y: 86, view: 'front', offset: 2 },
  'Suprapúbico (D)': { x: 45, y: 85, view: 'front' },
  'Suprapúbico (E)': { x: 55, y: 85, view: 'front' },
  'Pubis': { x: 50, y: 88, view: 'front' },
  'Saco de Douglas (D/E)': { x: 50, y: 85, view: 'front', offset: 5 },
  'Anexo (D)': { x: 44, y: 82, view: 'front' },
  'Anexo (E)': { x: 56, y: 82, view: 'front' },
  'Anexo': { x: 50, y: 82, view: 'front' },
  'Pudendo (D/E)': { x: 50, y: 87, view: 'front', offset: 5 },
  'Nervo Inguinal (D)': { x: 42, y: 82, view: 'front' },
  'Nervo Inguinal (E)': { x: 58, y: 82, view: 'front' },
  'Nervo Inguinal (D/E)': { x: 50, y: 82, view: 'front' },
  'Articulação': { x: 50, y: 50, view: 'front' },
  'Veia femural (D ou E)': { x: 50, y: 85, view: 'front' },
  'Veia Femural (D/E)': { x: 50, y: 85, view: 'front' },
  'Peri-hepático': { x: 42, y: 64, view: 'front', offset: 2 },
  'Costo-hepático': { x: 40, y: 60, view: 'front', offset: 2 },
  'Costo-diafragmático': { x: 50, y: 60, view: 'front', offset: 15 },
  'Diafragma': { x: 50, y: 60, view: 'front' },
  'Diafragma (D)': { x: 42, y: 60, view: 'front' },
  'Diafragma (E)': { x: 58, y: 60, view: 'front' },
  'Diafragma (D/E)': { x: 50, y: 60, view: 'front' },
  'Ligamento Hepático': { x: 45, y: 60, view: 'front' },
  'Epíplon (D/E) omento': { x: 50, y: 72, view: 'front', offset: 10 },
  'Epíplon': { x: 50, y: 72, view: 'front', offset: 10 },
  'Flanco (D/E)': { x: 50, y: 75, view: 'front', offset: 15 },
  'Condral (D)': { x: 40, y: 60, view: 'front' },
  'Condral (E)': { x: 60, y: 60, view: 'front' },
  'Costal (D)': { x: 35, y: 60, view: 'front' },
  'Costal (E)': { x: 65, y: 60, view: 'front' },
  'Costal Anterior (D)': { x: 35, y: 60, view: 'front' },
  'Costal Anterior (E)': { x: 65, y: 60, view: 'front' },
  'Peritôneo': { x: 50, y: 75, view: 'front', offset: 5 },
  'Peritôneo D e E': { x: 50, y: 75, view: 'front', offset: 5 },
  'Fossa Ilíaca': { x: 50, y: 78, view: 'front' },
  'Veia Porta': { x: 48, y: 65, view: 'front', offset: 2 },
  'Mesentério (D)': { x: 47, y: 73, view: 'front' },
  'Mesentério (E)': { x: 53, y: 73, view: 'front' },
  'Conducto Deferente': { x: 50, y: 88, view: 'front' },
  'Conducto Espermático': { x: 50, y: 88, view: 'front' },
  'Esfinter Uretral': { x: 50, y: 88, view: 'front' },
  'Clitóris': { x: 50, y: 88, view: 'front' },

  // Costas e Membros Superiores
  'Supraespinoso (D/E)': { x: 50, y: 40, view: 'back', offset: 10 },
  'Supraespinoso': { x: 50, y: 40, view: 'back' },
  'Escápula (D/E)': { x: 50, y: 48, view: 'back', offset: 10 },
  'Deltoide (D/E)': { x: 50, y: 45, view: 'front', offset: 18 },
  'Deltoide': { x: 50, y: 45, view: 'front' },
  'Úmero (D/E)': { x: 50, y: 52, view: 'front', offset: 18 },
  'Bursa (D/E)': { x: 50, y: 48, view: 'front', offset: 18 },
  'Bursa': { x: 50, y: 48, view: 'front' },
  'Cotovelo (D/E)': { x: 50, y: 58, view: 'front', offset: 20 },
  'Cotovelo': { x: 50, y: 58, view: 'front' },
  'Braquial (D/E)': { x: 50, y: 55, view: 'front', offset: 18 },
  'Cúbito (D/E)': { x: 50, y: 64, view: 'front', offset: 20 },
  'Rádio (D/E)': { x: 50, y: 64, view: 'front', offset: 18 },
  'Punho (D/E)': { x: 50, y: 70, view: 'front', offset: 18 },
  'Munheca': { x: 50, y: 70, view: 'front', offset: 18 },
  'Palma (D/E)': { x: 50, y: 75, view: 'front', offset: 18 },
  'Dedo Indicador (D/E)': { x: 50, y: 78, view: 'front', offset: 16 },
  'Quadrado lombar (D/E)': { x: 50, y: 72, view: 'back', offset: 8 },
  'Cervical': { x: 50, y: 35, view: 'back' },
  'Atlas': { x: 50, y: 32, view: 'back', offset: 2 },
  'Dorsal': { x: 50, y: 50, view: 'back' },
  'Lombar': { x: 50, y: 70, view: 'back' },
  'Dorsal 2': { x: 50, y: 42, view: 'back' },
  'Dorsal 3': { x: 50, y: 44, view: 'back' },
  'Dorsal 7': { x: 50, y: 52, view: 'back' },
  'Quarta Lombar (D)': { x: 45, y: 72, view: 'back' },
  'Quarta Lombar (E)': { x: 55, y: 72, view: 'back' },
  'Cálice renal (D/E)': { x: 50, y: 67, view: 'back', offset: 8 },
  'Rim (D)': { x: 40, y: 68, view: 'back' },
  'Rim (E)': { x: 60, y: 68, view: 'back' },
  'Rim direito': { x: 40, y: 68, view: 'back' },
  'Rim esquerdo': { x: 60, y: 68, view: 'back' },
  'Rim contralateral': { x: 50, y: 68, view: 'back' },
  'Rim do mesmo lado': { x: 50, y: 68, view: 'back' },
  'Rim (D/E)': { x: 50, y: 68, view: 'back', offset: 10 },
  'Rim': { x: 50, y: 68, view: 'back' },
  'Capsula Renal (D)': { x: 40, y: 68, view: 'back' },
  'Capsula Renal (E)': { x: 60, y: 68, view: 'back' },
  'Capsula Renal (D/E)': { x: 50, y: 68, view: 'back', offset: 10 },
  'Perirrenal (D/E)': { x: 50, y: 68, view: 'back', offset: 12 },
  'Perirrenal': { x: 50, y: 68, view: 'back' },
  'Cava (D/E)': { x: 50, y: 65, view: 'back', offset: 3 },
  'Latissimus Dorsal (D)': { x: 40, y: 55, view: 'back' },
  'Latissimus Dorsal (E)': { x: 60, y: 55, view: 'back' },
  'Retroaxiliar (D)': { x: 38, y: 48, view: 'back' },
  'Retroaxiliar (E)': { x: 62, y: 48, view: 'back' },
  'Ombro (D/E)': { x: 50, y: 43, view: 'front', offset: 15 },
  'Retro-Hepático': { x: 42, y: 64, view: 'back' },
  
  // Pélvis e Membros Inferiores
  'Trocânter maior (D/E)': { x: 50, y: 85, view: 'back', offset: 12 },
  'Trocânter Maior': { x: 50, y: 85, view: 'back' },
  'Trocânter menor (D/E)': { x: 50, y: 88, view: 'front', offset: 8 },
  'Glúteo (D/E)': { x: 50, y: 82, view: 'back', offset: 10 },
  'Glúteo Menor (D/E)': { x: 50, y: 80, view: 'back', offset: 10 },
  'Ciático (D/E)': { x: 50, y: 90, view: 'back', offset: 8 },
  'Poplíteo (D/E)': { x: 50, y: 105, view: 'back', offset: 8 },
  'Calcanhar (D)': { x: 45, y: 130, view: 'back' },
  'Calcanhar (E)': { x: 55, y: 130, view: 'back' },
  'Calcanhar (D/E)': { x: 50, y: 130, view: 'back', offset: 5 },
  'Aquiles (D/E)': { x: 50, y: 125, view: 'back', offset: 5 },
  'Plexo Lombar (D)': { x: 45, y: 75, view: 'back' },
  'Plexo Lombar (E)': { x: 55, y: 75, view: 'back' },
  'Ilíaco (D/E)': { x: 50, y: 78, view: 'back', offset: 10 },
  'Interilíaco': { x: 50, y: 78, view: 'back' },
  'Quadril (D/E)': { x: 50, y: 83, view: 'back', offset: 13 },
  'Ísquio (D/E)': { x: 50, y: 88, view: 'back', offset: 8 },
  'Rama isquiática (D/E)': { x: 50, y: 90, view: 'back', offset: 6 },
  'Insisura Ciática (D)': { x: 45, y: 85, view: 'back' },
  'Insisura Ciática (E)': { x: 55, y: 85, view: 'back' },
  'Veia femoral do mesmo lado': { x: 50, y: 85, view: 'front' },
  'Adutor': { x: 50, y: 90, view: 'front', offset: 5 },
  'Quadríceps (D/E)': { x: 50, y: 95, view: 'front', offset: 8 },
  'Quadriceps femural (coxa)': { x: 50, y: 95, view: 'front' },
  'Tensor da fascia lata (D)': { x: 38, y: 85, view: 'front' },
  'Tensor da fascia lata (E)': { x: 62, y: 85, view: 'front' },
  'Retro Tensor da Fascia Lata (D)': { x: 38, y: 85, view: 'back' },
  'Retro Tensor da Fascia Lata (E)': { x: 62, y: 85, view: 'back' },
  'Ligamento externo do joelho (D/E)': { x: 50, y: 102, view: 'front', offset: 10 },
  'Tíbia (D/E)': { x: 50, y: 115, view: 'front', offset: 8 },
  'Fíbula': { x: 50, y: 115, view: 'front', offset: 10 },
  'Retroplantar (D)': { x: 47, y: 135, view: 'back' },
  'Retroplantar (E)': { x: 53, y: 135, view: 'back' },
  'Nervo Femoral (D)': { x: 43, y: 88, view: 'front' },
  'Nervo Femoral (E)': { x: 57, y: 88, view: 'front' },

  // Reservatórios
  'Mordida': { x: 50, y: 33, view: 'front' },
  'Nutrícia (D/E)': { x: 50, y: 35, view: 'front', offset: 5 },
  'Solo Pelvico (D)': { x: 45, y: 88, view: 'front' },
  'Solo Pelvico (E)': { x: 55, y: 88, view: 'front' },
  'Vacina': { x: 35, y: 45, view: 'front' },
  'Pulmão (D ou E)': { x: 50, y: 50, view: 'front' },
  'Pulmão (D/E)': { x: 50, y: 50, view: 'front' },
  'Pleura D e E': { x: 50, y: 55, view: 'front', offset: 15 },
  'Pleura': { x: 50, y: 55, view: 'front' },
  'Cicatriz (corte cirurgias, cotos de membros e extrações)': { x: 50, y: 70, view: 'front' }
};
