export const POINT_DEFINITIONS: { [key: string]: { x: number; y: number; view: 'front' | 'back'; offset?: number } } = {
  // Cabeça
  'Parietal Direito': { x: 40, y: 20, view: 'front' },
  'Parietal Esquerdo': { x: 60, y: 20, view: 'front' },
  'Pineal': { x: 50, y: 22, view: 'front' },
  'Hipófise': { x: 50, y: 25, view: 'front' },
  'Bulbo Raquidiano': { x: 50, y: 28, view: 'back' },
  'Ouvido Direito': { x: 38, y: 26, view: 'front' },
  'Ouvido Esquerdo': { x: 62, y: 26, view: 'front' },
  'Língua (D ou E)': { x: 50, y: 32, view: 'front' },
  // Pescoço / Tórax (Frente)
  'Timo': { x: 50, y: 40, view: 'front' },
  'Nervo Vago': { x: 50, y: 35, view: 'front' },
  'Clavícula Média': { x: 50, y: 38, view: 'front', offset: 10 },
  'Axila': { x: 50, y: 45, view: 'front', offset: 20 },
  'Axila (D/E)': { x: 50, y: 45, view: 'front', offset: 20 },
  'Subclávia': { x: 50, y: 40, view: 'front', offset: 15 },
  'Subclávia (D/E)': { x: 50, y: 40, view: 'front', offset: 15 },
  'Deltoide': { x: 50, y: 38, view: 'front', offset: 32 },
  'Deltoide (D/E)': { x: 50, y: 38, view: 'front', offset: 32 },
  'Úmero': { x: 50, y: 55, view: 'front', offset: 35 },
  'Úmero (D/E)': { x: 50, y: 55, view: 'front', offset: 35 },
  'Bursa': { x: 50, y: 42, view: 'front', offset: 30 },
  'Bursa (D/E)': { x: 50, y: 42, view: 'front', offset: 30 },
  'Cotovelo': { x: 50, y: 70, view: 'front', offset: 40 },
  'Cotovelo (D/E)': { x: 50, y: 70, view: 'front', offset: 40 },
  'Braquial': { x: 50, y: 65, view: 'front', offset: 38 },
  'Braquial (D/E)': { x: 50, y: 65, view: 'front', offset: 38 },
  'Cúbito': { x: 50, y: 80, view: 'front', offset: 42 },
  'Cúbito (D/E)': { x: 50, y: 80, view: 'front', offset: 42 },
  'Rádio': { x: 50, y: 82, view: 'front', offset: 45 },
  'Rádio (D/E)': { x: 50, y: 82, view: 'front', offset: 45 },
  'Punho': { x: 50, y: 90, view: 'front', offset: 46 },
  'Punho (D/E)': { x: 50, y: 90, view: 'front', offset: 46 },
  'Palma': { x: 50, y: 95, view: 'front', offset: 48 },
  'Palma (D/E)': { x: 50, y: 95, view: 'front', offset: 48 },
  'Dedo Indicador': { x: 50, y: 100, view: 'front', offset: 50 },
  'Dedo Indicador (D/E)': { x: 50, y: 100, view: 'front', offset: 50 },
  // Pescoço / Tórax (Costas)
  'Primeira Cervical': { x: 50, y: 30, view: 'back' },
  'Supraespinoso': { x: 50, y: 38, view: 'back', offset: 15 },
  'Supraespinhoso': { x: 50, y: 38, view: 'back', offset: 15 },
  'Supraespinhoso (D/E)': { x: 50, y: 38, view: 'back', offset: 15 },
  'Escápula': { x: 50, y: 45, view: 'back', offset: 10 },
  'Quarta Dorsal': { x: 50, y: 48, view: 'back' },
  // Abdômen (Frente)
  'Fígado': { x: 40, y: 60, view: 'front' },
  'Apêndice': { x: 42, y: 75, view: 'front', offset: 3 },
  'Ceco': { x: 42, y: 78, view: 'front', offset: 4 },
  'Pleura Direita': { x: 40, y: 55, view: 'front' },
  'Pleura (D/E)': { x: 50, y: 55, view: 'front', offset: 10 },
  'Pleura': { x: 50, y: 55, view: 'front', offset: 10 },
  'Costo Diafragmático': { x: 50, y: 65, view: 'front', offset: 15 },
  'Duodeno': { x: 50, y: 68, view: 'front' },
  'Estômago': { x: 55, y: 65, view: 'front' },
  'Píloro': { x: 48, y: 68, view: 'front' },
  'Íliaco': { x: 50, y: 80, view: 'front', offset: 8 },
  'Ligamento Pancreático': { x: 58, y: 68, view: 'front' },
  'Baço': { x: 60, y: 65, view: 'front', offset: 4 },
  'Bexiga': { x: 50, y: 85, view: 'front' },
  'Cabeça do Pâncreas': { x: 52, y: 67, view: 'front' },
  'Cauda do Pâncreas': { x: 58, y: 66, view: 'front' },
  'Pâncreas': { x: 55, y: 66, view: 'front' },
  'Pâncreas (Corpo)': { x: 55, y: 66, view: 'front' },
  'Ponta do pâncreas': { x: 62, y: 66, view: 'front' },
  'Cólon descendente': { x: 60, y: 80, view: 'front' },
  'Cólon sigmoide': { x: 55, y: 88, view: 'front' },
  'Xifoide': { x: 50, y: 58, view: 'front' },
  'Testículo': { x: 50, y: 92, view: 'front', offset: 4 },
  'Testículo (D ou E)': { x: 50, y: 92, view: 'front', offset: 4 },
  'Testículo/vagina (D/E)': { x: 50, y: 92, view: 'front', offset: 4 },
  'Testículo/vagina': { x: 50, y: 92, view: 'front', offset: 4 },
  'Próstata': { x: 50, y: 94, view: 'front', offset: 5 },
  'Próstata/períneo': { x: 50, y: 94, view: 'front' },
  'Clitóris': { x: 50, y: 93, view: 'front' },
  'Ureter': { x: 50, y: 78, view: 'front', offset: 6 },
  'Ureter (D/E)': { x: 50, y: 78, view: 'front', offset: 6 },
  'Útero': { x: 50, y: 83, view: 'front', offset: 5 },
  'Ovário': { x: 50, y: 85, view: 'front', offset: 8 },
  'Ovário (D ou E)': { x: 50, y: 85, view: 'front', offset: 8 },
  'Ovário (D/E)': { x: 50, y: 85, view: 'front', offset: 8 },
  'Trompa': { x: 50, y: 84, view: 'front', offset: 7 },
  'Trompa (D/E)': { x: 50, y: 84, view: 'front', offset: 7 },
  'Trompa de Falópio (D/E)': { x: 50, y: 84, view: 'front', offset: 7 },
  'Saco de Douglas (D/E)': { x: 50, y: 96, view: 'front', offset: 5 },
  'Anexo (D)': { x: 50, y: 86, view: 'front', offset: 10 },
  'Anexo (E)': { x: 50, y: 86, view: 'front', offset: 10 },
  'Pudendo (D/E)': { x: 50, y: 95, view: 'front', offset: 4 },
  'Pudendo': { x: 50, y: 95, view: 'front', offset: 4 },
  'Nervo Inguinal (D)': { x: 42, y: 95, view: 'front' },
  'Nervo Inguinal (E)': { x: 58, y: 95, view: 'front' },
  'Nervo Inguinal (D/E)': { x: 50, y: 95, view: 'front', offset: 8 },
  'Articulação': { x: 35, y: 110, view: 'front', offset: 30 },
  'Trocânter menor (D/E)': { x: 50, y: 105, view: 'front', offset: 10 },
  'Adutor': { x: 50, y: 108, view: 'front', offset: 8 },
  'Tíbia (D/E)': { x: 50, y: 128, view: 'front', offset: 6 },
  'Tíbia': { x: 50, y: 128, view: 'front', offset: 6 },
  'Calcâneo (D/E)': { x: 50, y: 150, view: 'back', offset: 4 },
  'Calcâneo': { x: 50, y: 150, view: 'back', offset: 4 },
  'Aquiles (D/E)': { x: 50, y: 145, view: 'back', offset: 4 },
  'Aquiles': { x: 50, y: 145, view: 'back', offset: 4 },
  'Ligamento externo do joelho (D/E)': { x: 50, y: 115, view: 'front', offset: 12 },
  'Tensor da fascia lata (D)': { x: 34, y: 102, view: 'front' },
  'Tensor da fascia lata (E)': { x: 66, y: 102, view: 'front' },
  'Trocânter maior (D/E)': { x: 50, y: 105, view: 'front', offset: 18 },
  'Trocânter maior': { x: 50, y: 105, view: 'front', offset: 18 },
  // Abdômen (Costas)
  'Reto': { x: 50, y: 90, view: 'back', offset: 4 },
  'Ânus': { x: 50, y: 94, view: 'back', offset: 4 },
  'Rim Direito': { x: 42, y: 70, view: 'back' },
  'Rim Esquerdo': { x: 58, y: 70, view: 'back' },
  'Rim do mesmo lado': { x: 50, y: 70, view: 'back', offset: 8 },
  'Suprarrenais': { x: 58, y: 68, view: 'back' },
  'Glúteo': { x: 50, y: 85, view: 'back', offset: 8 },
  'Sacro': { x: 50, y: 82, view: 'back' },
  'Quarta Lombar': { x: 50, y: 78, view: 'back' },
  'Quadrado lombar (D/E)': { x: 50, y: 75, view: 'back', offset: 10 },
  // Pernas
  'Maléolo Interno': { x: 50, y: 140, view: 'front', offset: 4 },
  'Poplíteo': { x: 50, y: 115, view: 'back', offset: 4 },
  'Poplíteo (D/E)': { x: 50, y: 115, view: 'back', offset: 4 },
  'Calcanhar': { x: 50, y: 150, view: 'back', offset: 4 },
  'Veia Femural (D/E)': { x: 50, y: 105, view: 'front', offset: 12 },
  'Veia femural (D ou E)': { x: 50, y: 105, view: 'front', offset: 12 },
  // Casos Especiais - o componente lida com a lógica
  'Rim Contralateral': { x: 0, y: 0, view: 'back' },
};