export const POINT_DEFINITIONS: { [key: string]: { x: number; y: number; view: 'front' | 'back'; offset?: number } } = {
  // Cabeça
  'Parietal Direito': { x: 40, y: 20, view: 'front' },
  'Parietal Esquerdo': { x: 60, y: 20, view: 'front' },
  'Pineal': { x: 50, y: 22, view: 'front' },
  'Hipófise': { x: 50, y: 25, view: 'front' },
  'Bulbo Raquidiano': { x: 50, y: 28, view: 'back' },
  'Bulbo raquidiano': { x: 50, y: 28, view: 'back' },
  'Cerebelo (C)': { x: 50, y: 24, view: 'back' },
  'Cerebelo': { x: 50, y: 24, view: 'back' },
  'Cerebelo (D/E)': { x: 50, y: 24, view: 'back', offset: 6 },
  'Occipital': { x: 50, y: 18, view: 'back' },
  'Occipital (D/E)': { x: 50, y: 18, view: 'back', offset: 6 },
  'Temporal': { x: 50, y: 22, view: 'front', offset: 12 },
  'Temporal (D/E)': { x: 50, y: 22, view: 'front', offset: 12 },
  'Temporal D': { x: 38, y: 22, view: 'front', offset: 2 },
  'Temporal E': { x: 62, y: 22, view: 'front', offset: 2 },
  'Temporoccipital (D)': { x: 40, y: 21, view: 'back' },
  'Temporoccipital (E)': { x: 60, y: 21, view: 'back' },
  'Seio frontal (D)': { x: 44, y: 18, view: 'front' },
  'Seio frontal (E)': { x: 56, y: 18, view: 'front' },
  'Interciliar': { x: 50, y: 18, view: 'front' },
  'Supraciliar': { x: 50, y: 16, view: 'front' },
  'Seio paranasal (D)': { x: 44, y: 28, view: 'front' },
  'Seio paranasal (E)': { x: 56, y: 28, view: 'front' },
  'Polo (D)': { x: 40, y: 14, view: 'front' },
  'Polo (E)': { x: 60, y: 14, view: 'front' },
  'Craneal (D)': { x: 35, y: 12, view: 'front' },
  'Craneal (E)': { x: 65, y: 12, view: 'front' },
  'Lacrimal (D)': { x: 48, y: 24, view: 'front' },
  'Lacrimal (E)': { x: 52, y: 24, view: 'front' },
  'Canto do olho (D)': { x: 46, y: 24, view: 'front' },
  'Canto do olho (E)': { x: 54, y: 24, view: 'front' },
  'Pálpebra (D)': { x: 43, y: 24, view: 'front' },
  'Pálpebra (E)': { x: 57, y: 24, view: 'front' },
  'Piso orbital (D)': { x: 45, y: 26, view: 'front' },
  'Piso orbital (E)': { x: 55, y: 26, view: 'front' },
  'Piso Orbital': { x: 50, y: 26, view: 'front', offset: 5 },
  'Quiasma (D)': { x: 47, y: 22, view: 'front' },
  'Quiasma (E)': { x: 53, y: 22, view: 'front' },
  'Polígono de Willis (D)': { x: 44, y: 22, view: 'front' },
  'Polígono de Willis (E)': { x: 56, y: 22, view: 'front' },
  'Polígono de Willis': { x: 50, y: 22, view: 'front', offset: 6 },
  'Nariz (D)': { x: 48, y: 28, view: 'front' },
  'Nariz (E)': { x: 52, y: 28, view: 'front' },
  'Malar (D)': { x: 42, y: 30, view: 'front' },
  'Malar (E)': { x: 58, y: 30, view: 'front' },
  'Ângulo (D)': { x: 39, y: 33, view: 'front' },
  'Ângulo (E)': { x: 61, y: 33, view: 'front' },
  'Canto da boca (D)': { x: 46, y: 32, view: 'front' },
  'Canto da boca (E)': { x: 54, y: 32, view: 'front' },
  'Ouvido Direito': { x: 38, y: 26, view: 'front' },
  'Ouvido Esquerdo': { x: 62, y: 26, view: 'front' },
  'Língua (D ou E)': { x: 50, y: 32, view: 'front' },
  'Pinta': { x: 50, y: 15, view: 'front' },
  'Sobrancelha (D)': { x: 43, y: 21, view: 'front' },
  'Sobrancelha (E)': { x: 57, y: 21, view: 'front' },
  // Pescoço / Tórax (Frente)
  'Amígdala palatina (Angina)': { x: 50, y: 35, view: 'front', offset: 4 },
  'Amígdala palatina (Angina) (D/E)': { x: 50, y: 35, view: 'front', offset: 4 },
  'Pescoço': { x: 50, y: 36, view: 'front' },
  'Pescoço (D/E)': { x: 50, y: 36, view: 'front', offset: 8 },
  'Plexo Cervical': { x: 50, y: 34, view: 'front', offset: 10 },
  'Laringe': { x: 50, y: 38, view: 'front' },
  'Laringe (S)': { x: 50, y: 37, view: 'front' },
  'Laringe (Inf)': { x: 50, y: 39, view: 'front' },
  'Esterno cleido mastoideo (D)': { x: 44, y: 36, view: 'front' },
  'Esterno cleido mastoideo (E)': { x: 56, y: 36, view: 'front' },
  'Carótida': { x: 50, y: 38, view: 'front', offset: 3 },
  'Carótida (D)': { x: 50, y: 38, view: 'front', offset: 3 },
  'Carótida (E)': { x: 50, y: 38, view: 'front', offset: 3 },
  'Primeira Costela': { x: 50, y: 42, view: 'front', offset: 8 },
  'Primeira Costela (D)': { x: 50, y: 42, view: 'front', offset: 8 },
  'Primeira Costela (E)': { x: 50, y: 42, view: 'front', offset: 8 },
  'Manubrio de Esterno': { x: 50, y: 41, view: 'front', offset: 3 },
  'Esterno': { x: 50, y: 55, view: 'front' },
  'Traqueia': { x: 50, y: 41, view: 'front' },
  'Traqueia (D/E)': { x: 50, y: 38, view: 'front' },
  'Esôfago': { x: 50, y: 50, view: 'front' },
  'Esôfago (E)': { x: 52, y: 50, view: 'front' },
  'Esôfago (D)': { x: 48, y: 50, view: 'front' },
  'Cardias': { x: 48, y: 56, view: 'front' },
  'Hiato esofágico': { x: 50, y: 58, view: 'front' },
  'Carina': { x: 50, y: 43, view: 'front', offset: 5 },
  'Carina (D)': { x: 50, y: 43, view: 'front', offset: 5 },
  'Carina (E)': { x: 50, y: 43, view: 'front', offset: 5 },
  'Timo': { x: 50, y: 40, view: 'front' },
  'Nervo Vago': { x: 50, y: 35, view: 'front' },
  'Clavícula Média': { x: 50, y: 38, view: 'front', offset: 10 },
  'Axila': { x: 50, y: 45, view: 'front', offset: 20 },
  'Axila (D/E)': { x: 50, y: 45, view: 'front', offset: 20 },
  'Subclávia': { x: 50, y: 40, view: 'front', offset: 15 },
  'Subclávia (D/E)': { x: 50, y: 40, view: 'front', offset: 15 },
  'Deltoide': { x: 50, y: 38, view: 'front', offset: 32 },
  'Deltoide (D/E)': { x: 50, y: 38, view: 'front', offset: 32 },
  'Ombro (D/E)': { x: 50, y: 38, view: 'front', offset: 38 },
  'Úmero': { x: 50, y: 55, view: 'front', offset: 35 },
  'Úmero (D/E)': { x: 50, y: 55, view: 'front', offset: 35 },
  'Bursa': { x: 50, y: 42, view: 'front', offset: 30 },
  'Bursa (D/E)': { x: 50, y: 42, view: 'front', offset: 30 },
  'Cotovelo': { x: 50, y: 70, view: 'front', offset: 40 },
  'Cotovelo (D/E)': { x: 50, y: 70, view: 'front', offset: 40 },
  'Braquial': { x: 50, y: 65, view: 'front', offset: 38 },
  'Braquial (D/E)': { x: 50, y: 65, view: 'front', offset: 38 },
  'Cúbito': { x: 50, y: 80, view: 'front', offset: 42 },
  'Cúbito (D/E)': { x: 50, y: 80, view: 'front', offset: 42 },
  'Rádio': { x: 50, y: 82, view: 'front', offset: 45 },
  'Rádio (D/E)': { x: 50, y: 82, view: 'front', offset: 45 },
  'Punho': { x: 50, y: 90, view: 'front', offset: 46 },
  'Punho (D/E)': { x: 50, y: 90, view: 'front', offset: 46 },
  'Munheca': { x: 50, y: 90, view: 'front', offset: 46 },
  'Palma': { x: 50, y: 95, view: 'front', offset: 48 },
  'Palma (D/E)': { x: 50, y: 95, view: 'front', offset: 48 },
  'Dedo Indicador': { x: 50, y: 100, view: 'front', offset: 50 },
  'Dedo Indicador (D/E)': { x: 50, y: 100, view: 'front', offset: 50 },
  'Toda frente do torax': { x: 50, y: 45, view: 'front' },
  'Condral (D)': { x: 42, y: 58, view: 'front' },
  'Condral (E)': { x: 58, y: 58, view: 'front' },
  'Costal (D)': { x: 38, y: 62, view: 'front' },
  'Costal (E)': { x: 62, y: 62, view: 'front' },
  'Costal Anterior (D)': { x: 40, y: 62, view: 'front' },
  'Costal Anterior (E)': { x: 60, y: 62, view: 'front' },
  'Flanco (D/E)': { x: 32, y: 72, view: 'front' },
  'Flanco': { x: 68, y: 72, view: 'front' },
  'Diafragma (D/E)': { x: 50, y: 60, view: 'front', offset: 12 },
  'Diafragma (D)': { x: 40, y: 60, view: 'front' },
  'Diafragma (E)': { x: 60, y: 60, view: 'front' },
  'Ligamento Hepático': { x: 42, y: 62, view: 'front' },
  'Sino(nodo) Atrioventricular': { x: 46, y: 50, view: 'front' },
  'Epíplon (D/E) omento': { x: 50, y: 72, view: 'front', offset: 10 },
  'Epíplon': { x: 50, y: 72, view: 'front', offset: 10 },
  'Pericárdio': { x: 48, y: 52, view: 'front', offset: 5 },
  'Coronárias': { x: 47, y: 53, view: 'front' },
  'Pulmão (geralmente esquerdo)': { x: 62, y: 48, view: 'front' },
  // Pescoço / Tórax (Costas)
  'Primeira Cervical': { x: 50, y: 30, view: 'back' },
  'Cervical': { x: 50, y: 32, view: 'back' },
  'Atlas': { x: 50, y: 30, view: 'back', offset: 6 },
  'Supraespinoso': { x: 50, y: 38, view: 'back', offset: 15 },
  'Supraespinhoso': { x: 50, y: 38, view: 'back', offset: 15 },
  'Supraespinhoso (D/E)': { x: 50, y: 38, view: 'back', offset: 15 },
  'Escápula': { x: 50, y: 45, view: 'back', offset: 10 },
  'Escápula (D/E)': { x: 50, y: 45, view: 'back', offset: 10 },
  'Quarta Dorsal': { x: 50, y: 48, view: 'back' },
  'Dorsal': { x: 50, y: 55, view: 'back' },
  'Dorsal 2': { x: 50, y: 42, view: 'back', offset: 3 },
  'Dorsal 3': { x: 50, y: 46, view: 'back' },
  'Dorsal 7': { x: 50, y: 62, view: 'back' },
  // Abdômen (Frente)
  'Fígado': { x: 40, y: 60, view: 'front' },
  'Apêndice': { x: 42, y: 75, view: 'front', offset: 3 },
  'Ceco': { x: 42, y: 78, view: 'front', offset: 4 },
  'Pleura Direita': { x: 40, y: 55, view: 'front' },
  'Pleura (D/E)': { x: 50, y: 55, view: 'front', offset: 10 },
  'Pleura': { x: 50, y: 55, view: 'front', offset: 10 },
  'Pulmão (D/E)': { x: 50, y: 48, view: 'front', offset: 12 },
  'Cava (D/E)': { x: 54, y: 58, view: 'front', offset: 8 },
  'Costo Diafragmático': { x: 50, y: 65, view: 'front', offset: 15 },
  'Duodeno': { x: 50, y: 68, view: 'front' },
  'Estômago': { x: 55, y: 65, view: 'front' },
  'Píloro': { x: 48, y: 68, view: 'front' },
  'Íliaco': { x: 50, y: 80, view: 'front', offset: 8 },
  'Ilíaco': { x: 50, y: 80, view: 'front', offset: 8 },
  'Ilíaco (D/E)': { x: 50, y: 80, view: 'front', offset: 8 },
  'Ligamento Pancreático': { x: 58, y: 68, view: 'front' },
  'Baço': { x: 60, y: 65, view: 'front', offset: 4 },
  'Bexiga': { x: 50, y: 85, view: 'front' },
  'Pubis': { x: 50, y: 92, view: 'front' },
  'Cabeça do Pâncreas': { x: 52, y: 67, view: 'front' },
  'Cauda do Pâncreas': { x: 58, y: 66, view: 'front' },
  'Pâncreas': { x: 55, y: 66, view: 'front' },
  'Pancreas': { x: 55, y: 66, view: 'front' },
  'Pâncreas (Corpo)': { x: 55, y: 66, view: 'front' },
  'Ponta do pâncreas': { x: 62, y: 66, view: 'front' },
  'Ampola Hepatopancreática': { x: 52, y: 69, view: 'front' },
  'Ligamento do Pâncreas': { x: 58, y: 68, view: 'front' },
  'Mesentério (D)': { x: 46, y: 73, view: 'front' },
  'Mesentério (E)': { x: 54, y: 73, view: 'front' },
  'Fossa Ilíaca': { x: 38, y: 82, view: 'front' },
  'Peripancreático (S)': { x: 55, y: 64, view: 'front' },
  'Peripancreático (Inf)': { x: 55, y: 68, view: 'front' },
  'Esfinter Uretral': { x: 50, y: 88, view: 'front', offset: 3 },
  'Conducto Deferente': { x: 45, y: 90, view: 'front' },
  'Conducto Espermático': { x: 50, y: 91, view: 'front', offset: 5 },
  'Cólon descendente': { x: 60, y: 80, view: 'front' },
  'Colon Descendente': { x: 60, y: 80, view: 'front' },
  'Cólon sigmoide': { x: 55, y: 88, view: 'front' },
  'Xifoide': { x: 50, y: 58, view: 'front' },
  'Testículo': { x: 50, y: 92, view: 'front', offset: 4 },
  'Testículo (D ou E)': { x: 50, y: 92, view: 'front', offset: 4 },
  'Testículo/vagina (D/E)': { x: 50, y: 92, view: 'front', offset: 4 },
  'Testículo/vagina': { x: 50, y: 92, view: 'front', offset: 4 },
  'Próstata': { x: 50, y: 94, view: 'front', offset: 5 },
  'Próstata/períneo': { x: 50, y: 94, view: 'front' },
  'Clitóris': { x: 50, y: 93, view: 'front' },
  'Ureter': { x: 50, y: 78, view: 'front', offset: 6 },
  'Ureter (D/E)': { x: 50, y: 78, view: 'front', offset: 6 },
  'Útero': { x: 50, y: 83, view: 'front', offset: 5 },
  'Ovário': { x: 50, y: 85, view: 'front', offset: 8 },
  'Ovário (D ou E)': { x: 50, y: 85, view: 'front', offset: 8 },
  'Ovário (D/E)': { x: 50, y: 85, view: 'front', offset: 8 },
  'Trompa': { x: 50, y: 84, view: 'front', offset: 7 },
  'Trompa (D/E)': { x: 50, y: 84, view: 'front', offset: 7 },
  'Trompa de Falópio (D/E)': { x: 50, y: 84, view: 'front', offset: 7 },
  'Saco de Douglas (D/E)': { x: 50, y: 96, view: 'front', offset: 5 },
  'Anexo (D)': { x: 50, y: 86, view: 'front', offset: 10 },
  'Anexo (E)': { x: 50, y: 86, view: 'front', offset: 10 },
  'Anexo': { x: 50, y: 86, view: 'front', offset: 10 },
  'Pudendo (D/E)': { x: 50, y: 95, view: 'front', offset: 4 },
  'Pudendo': { x: 50, y: 95, view: 'front', offset: 4 },
  'Nervo Inguinal (D)': { x: 42, y: 95, view: 'front' },
  'Nervo Inguinal (E)': { x: 58, y: 95, view: 'front' },
  'Nervo Inguinal (D/E)': { x: 50, y: 95, view: 'front', offset: 8 },
  'Nervo Femural': { x: 50, y: 100, view: 'front', offset: 10 },
  'Nervo Femoral': { x: 50, y: 100, view: 'front', offset: 10 },
  'Articulação': { x: 35, y: 110, view: 'front', offset: 30 },
  'Trocânter menor (D/E)': { x: 50, y: 105, view: 'front', offset: 10 },
  'Adutor': { x: 50, y: 108, view: 'front', offset: 8 },
  'Tíbia (D/E)': { x: 50, y: 128, view: 'front', offset: 6 },
  'Tíbia': { x: 50, y: 128, view: 'front', offset: 6 },
  'Calcâneo (D/E)': { x: 50, y: 150, view: 'back', offset: 4 },
  'Calcâneo': { x: 50, y: 150, view: 'back', offset: 4 },
  'Aquiles (D/E)': { x: 50, y: 145, view: 'back', offset: 4 },
  'Aquiles': { x: 50, y: 145, view: 'back', offset: 4 },
  'Ligamento externo do joelho (D/E)': { x: 50, y: 115, view: 'front', offset: 12 },
  'Tensor da fascia lata (D)': { x: 34, y: 102, view: 'front' },
  'Tensor da fascia lata (E)': { x: 66, y: 102, view: 'front' },
  'Retro Tensor da Fascia Lata (D)': { x: 32, y: 105, view: 'front' },
  'Retro Tensor da Fascia Lata (E)': { x: 68, y: 105, view: 'front' },
  'Trocânter maior (D/E)': { x: 50, y: 105, view: 'front', offset: 18 },
  'Trocânter maior': { x: 50, y: 105, view: 'front', offset: 18 },
  'Quadril (D/E)': { x: 50, y: 90, view: 'front', offset: 15 },
  'Quadril': { x: 50, y: 90, view: 'front', offset: 15 },
  'Quadríceps (D/E)': { x: 50, y: 120, view: 'front', offset: 15 },
  'Quadríceps': { x: 50, y: 120, view: 'front', offset: 15 },
  'Ciático (D/E)': { x: 50, y: 100, view: 'back', offset: 12 },
  'Ciático': { x: 50, y: 100, view: 'back', offset: 12 },
  'Ísquio (D/E)': { x: 50, y: 95, view: 'back', offset: 6 },
  'Ísquio': { x: 50, y: 95, view: 'back', offset: 6 },
  'Cóccix (sup)': { x: 50, y: 96, view: 'back' },
  'Cóccix (inf)': { x: 50, y: 100, view: 'back' },
  // Abdômen (Costas)
  'Reto': { x: 50, y: 90, view: 'back', offset: 4 },
  'Ânus': { x: 50, y: 94, view: 'back', offset: 4 },
  'Rim Direito': { x: 42, y: 70, view: 'back' },
  'Rim (D)': { x: 42, y: 70, view: 'back' },
  'Rim Esquerdo': { x: 58, y: 70, view: 'back' },
  'Rim (E)': { x: 58, y: 70, view: 'back' },
  'Rim do mesmo lado': { x: 50, y: 70, view: 'back', offset: 8 },
  'Rim': { x: 50, y: 70, view: 'back', offset: 8 },
  'Rim (D/E)': { x: 50, y: 70, view: 'back', offset: 8 },
  'Suprarrenais': { x: 58, y: 68, view: 'back' },
  'Suprarrenal': { x: 50, y: 68, view: 'back' },
  'Suprarrenal (C)': { x: 50, y: 68, view: 'back' },
  'Suprarenal (C)': { x: 50, y: 68, view: 'back' },
  'Suprarrenal (D/E)': { x: 50, y: 68, view: 'back